apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediawiki
  name: mediawiki
spec:
  type: LoadBalancer
  ports:
  - name: "mediawiki-8000"
    port: 8000
    targetPort: 80
  selector:
    app: mediawiki