apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediawiki
    play: mediawiki
  name: mediawiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - image: mail2sandeepd/sd_mediawiki_1_39
        imagePullPolicy: Never
        name: mediawiki-pod
        ports:
        - containerPort: 80        
        volumeMounts:
          - mountPath: /var/www/html/images
            name: mediawiki-volume        
      restartPolicy: Always
      serviceAccountName: ""
      volumes: 
        - name: mediawiki-volume