apiVersion: v1
kind: Service
metadata:
  name: mediawiki-stateful
  labels:
    app: mediawiki-stateful
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: mediawiki-stateful
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mw-sts
spec:
  selector:
    matchLabels:
      app: mediawiki-stateful # has to match .spec.template.metadata.labels
  serviceName: "mediawiki-stateful"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mediawiki-stateful # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mediawiki-stateful
        image: mail2sandeepd/sd_mediawiki_1_39
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - mountPath: /var/www/html/images
          name: mediawiki-volume        
      volumes: 
        - name: mediawiki-volume